//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADCN {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADCN.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  ó 1 número.
        /// </summary>
        internal static string _1_numero {
            get {
                return ResourceManager.GetString("1_numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10 Años.
        /// </summary>
        internal static string _10_Años {
            get {
                return ResourceManager.GetString("10_Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 11 Años.
        /// </summary>
        internal static string _11_Años {
            get {
                return ResourceManager.GetString("11_Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12 Años.
        /// </summary>
        internal static string _12_Años {
            get {
                return ResourceManager.GetString("12_Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar.
        /// </summary>
        internal static string Activar {
            get {
                return ResourceManager.GetString("Activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENCONTRASTE TODAS LAS LETRAS! AVANZAS AL NIVEL.
        /// </summary>
        internal static string Avanzar_Nivel_Atencion1 {
            get {
                return ResourceManager.GetString("Avanzar_Nivel_Atencion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ENCONTRASTE A PIKACHU! AVANZAS AL NIVEL.
        /// </summary>
        internal static string Avanzar_Nivel_Atencion2 {
            get {
                return ResourceManager.GetString("Avanzar_Nivel_Atencion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AVANZAS AL NIVEL.
        /// </summary>
        internal static string Avanzar_Nivel_Atencion3 {
            get {
                return ResourceManager.GetString("Avanzar_Nivel_Atencion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TODAS TUS RESPUESTAS SON CORRECTAS! AVANZAS AL NIVEL.
        /// </summary>
        internal static string Avanzar_Nivel_Memoria2 {
            get {
                return ResourceManager.GetString("Avanzar_Nivel_Memoria2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡HAS COMPLETADO EL NIVEL FÁCIL! AVANZAS AL NIVEL.
        /// </summary>
        internal static string Avanzar_Nivel_Memoria3_1 {
            get {
                return ResourceManager.GetString("Avanzar_Nivel_Memoria3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡HAS COMPLETADO EL NIVEL DIFÍCIL! AVANZAS AL NIVEL.
        /// </summary>
        internal static string Avanzar_Nivel_Memoria3_2 {
            get {
                return ResourceManager.GetString("Avanzar_Nivel_Memoria3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para entrar a los juegos de Atención debe hacer clic en el botón que se encuentra en su izquierda con el nombre &quot;Juegos de Atención&quot;..
        /// </summary>
        internal static string Ayuda1 {
            get {
                return ResourceManager.GetString("Ayuda1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para entrar a los juegos de Memoria debe hacer clic en el botón que se encuentra en su izquierda con el nombre &quot;Juegos de Memoria&quot;..
        /// </summary>
        internal static string Ayuda2 {
            get {
                return ResourceManager.GetString("Ayuda2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para cambiar el tema de la aplicación, debe ingresar a configuración y seleccionar el modo que desea..
        /// </summary>
        internal static string Ayuda3 {
            get {
                return ResourceManager.GetString("Ayuda3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para activar o desactivar los sonidos de la aplicación, debe ingresar a configuración y elegir la opción que desee..
        /// </summary>
        internal static string Ayuda4 {
            get {
                return ResourceManager.GetString("Ayuda4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para cambiar el idioma a inglés o español, debe hacer clic en cualquiera de los botones que se encuentra en la parte de abajo del menú..
        /// </summary>
        internal static string Ayuda5 {
            get {
                return ResourceManager.GetString("Ayuda5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si usted desea abrir el sitio web de Maslow School, usted debe hacer clic en el logo de la institución que se encuentra en la parte superior del menú..
        /// </summary>
        internal static string Ayuda6 {
            get {
                return ResourceManager.GetString("Ayuda6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te damos la Bienvenida.
        /// </summary>
        internal static string Bienvenida {
            get {
                return ResourceManager.GetString("Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingeniería de Software.
        /// </summary>
        internal static string Carrera {
            get {
                return ResourceManager.GetString("Carrera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        internal static string Color_del_Texto {
            get {
                return ResourceManager.GetString("Color_del_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego: &quot;Colores y Significados&quot;.
        /// </summary>
        internal static string Colores_y_Significados {
            get {
                return ResourceManager.GetString("Colores_y_Significados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comodín.
        /// </summary>
        internal static string Comodin {
            get {
                return ResourceManager.GetString("Comodin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobar.
        /// </summary>
        internal static string Comprobar {
            get {
                return ResourceManager.GetString("Comprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuál es la respuesta correcta?.
        /// </summary>
        internal static string Cual_es_la_respuesta_correcta {
            get {
                return ResourceManager.GetString("Cual_es_la_respuesta_correcta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desactivar.
        /// </summary>
        internal static string Desactivar {
            get {
                return ResourceManager.GetString("Desactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrolladores: .
        /// </summary>
        internal static string Desarrolladores {
            get {
                return ResourceManager.GetString("Desarrolladores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego: &quot;¿Dónde está Pikachu?&quot;.
        /// </summary>
        internal static string Donde_esta_pikachu {
            get {
                return ResourceManager.GetString("Donde_esta_pikachu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego: &quot;Elegir la letra correcta&quot;.
        /// </summary>
        internal static string Elegir_la_letra_correcta {
            get {
                return ResourceManager.GetString("Elegir_la_letra_correcta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPEZAR.
        /// </summary>
        internal static string Empezar {
            get {
                return ResourceManager.GetString("Empezar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Coincide el significado de arriba con el color del texto?.
        /// </summary>
        internal static string Encabezado_juego_atencion3 {
            get {
                return ResourceManager.GetString("Encabezado_juego_atencion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentra la letra &apos;P&apos;.
        /// </summary>
        internal static string Encuentra_la_letra_P {
            get {
                return ResourceManager.GetString("Encuentra_la_letra_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentra las letras &apos;E&apos; y &apos;P&apos;.
        /// </summary>
        internal static string Encuentra_las_letras_E_y_P {
            get {
                return ResourceManager.GetString("Encuentra_las_letras_E_y_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentra las letras &apos;I&apos;, &apos;G&apos; y &apos;S&apos;.
        /// </summary>
        internal static string Encuentra_las_letras_I_G_y_S {
            get {
                return ResourceManager.GetString("Encuentra_las_letras_I_G_y_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentra las letras &apos;T&apos;, &apos;K&apos; y el número &apos;8&apos;.
        /// </summary>
        internal static string Encuentra_las_letras_T_K_8 {
            get {
                return ResourceManager.GetString("Encuentra_las_letras_T_K_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba las provincias que corresponden a las imágenes.
        /// </summary>
        internal static string Escriba_las_provincias_que_corresponden_a_las_imagenes {
            get {
                return ResourceManager.GetString("Escriba_las_provincias_que_corresponden_a_las_imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahora escribe la frase, continuando con la historia.
        /// </summary>
        internal static string Escribe_la_frase {
            get {
                return ResourceManager.GetString("Escribe_la_frase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡FELICIDADES! HAS ACABADO EL JUEGO.
        /// </summary>
        internal static string Fin_del_juego {
            get {
                return ResourceManager.GetString("Fin_del_juego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego: &quot;Había una vez&quot;.
        /// </summary>
        internal static string Habia_una_vez {
            get {
                return ResourceManager.GetString("Habia_una_vez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Había una vez,una ballena llamada Elena,que era gorda y buena,y nada por los mares,como una sirena.
        /// </summary>
        internal static string Historia1_ballena {
            get {
                return ResourceManager.GetString("Historia1_ballena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Había una vez,una jirafa llamada Rafaela,que usaba las gafas de su abuelo,porque desde allá arribota,no ve hache ni jota,que creyó que un pino,era un jirafo muy fino.
        /// </summary>
        internal static string Historia2_jirafa {
            get {
                return ResourceManager.GetString("Historia2_jirafa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Había una vez,un gato llamado Ruperto,que la casa revisa,porque un ratoncito,ronca en la repisa,busca despacito,en todos los rincones,pero el gato dormilón,se durmió en un rincón,y ron ron ron,ronca y ronca don ratón.
        /// </summary>
        internal static string Historia3_gato {
            get {
                return ResourceManager.GetString("Historia3_gato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrucciones.
        /// </summary>
        internal static string Instrucciones {
            get {
                return ResourceManager.GetString("Instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego consta de diferentes niveles, en los cuales, deberás hacer clic únicamente en las letras que se te pide, y al momento en que encuentres todas la letras pedidas, avanzarás de nivel. En caso de que hagas clic en alguna letra que no se te pidió, se te restarán puntos. Recuerda que mientras más rápido acabes, más puntos tendrás..
        /// </summary>
        internal static string Instrucciones1 {
            get {
                return ResourceManager.GetString("Instrucciones1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego consta de diferentes niveles, en los cuales, habrá un Pikachu escondido entre muchas personas. Debes hacer clic encima de él al momento que lo encuentres, y de esta forma avanzarás al siguiente nivel. En caso de hacer clic en otra parte de la imagen, se te restarán puntos. Recuerda que mientras más rápido acabes, más puntos tendrás..
        /// </summary>
        internal static string Instrucciones2 {
            get {
                return ResourceManager.GetString("Instrucciones2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se te mostrarán dos palabras, tendrás que fijarte en el significado de la palabra de arriba y verificar si coincide con el color de la palabra de abajo. Es decir, si arriba dice &apos;Azul&apos; y el color de la palabra de abajo es azul también, debes hacer clic en el botón SI, caso contrario, debes hacer clic en NO. Mientras avances de nivel, habrán más colores. Recuerda que mientras más rápido acabes, más puntos tendrás..
        /// </summary>
        internal static string Instrucciones3 {
            get {
                return ResourceManager.GetString("Instrucciones3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego consta de dos niveles, en los cuales tendrás multiplicaciones aleatorias de dos números. Abajo de la multiplicación se te mostrarán 4 respuestas distintas. Para avanzar a la siguiente operación, deberás hacer clic en la respuesta correcta, caso contrario se te restarán puntos. Recuerda que mientras más rápido acabes, más puntos tendrás..
        /// </summary>
        internal static string Instrucciones4 {
            get {
                return ResourceManager.GetString("Instrucciones4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego consta de 3 niveles, en los cuales se te mostrarán diferentes imágenes de tres distintas provincias del Ecuador. Debes memorizarlas y hacer clic en \&quot;Listo\&quot;, luego se te mostrará una imagen de cada provincia y tu deberás escribir a cuál pertenece..
        /// </summary>
        internal static string Instrucciones5 {
            get {
                return ResourceManager.GetString("Instrucciones5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego consta de 3 niveles. En los cuales deberás memorizar la frase y hacer clic en &apos;Siguiente&apos;, a continuación deberás escribir la frase que memorizaste. En caso de que hayas escrito correctamente la frase, se te mostrará la siguiente frase de la historia, que también deberás memorizar, y a continuación deberás escribir lo que ya habías escrito pero agregando la nueva frase. Y así hasta que terminarás la historia. Recuerda que mientras más rápido acabes, más puntos tendrás..
        /// </summary>
        internal static string Instrucciones6 {
            get {
                return ResourceManager.GetString("Instrucciones6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juegos de Atención.
        /// </summary>
        internal static string Juegos_de_Atencion {
            get {
                return ResourceManager.GetString("Juegos_de_Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juegos de Memoria.
        /// </summary>
        internal static string Juegos_de_Memoria {
            get {
                return ResourceManager.GetString("Juegos_de_Memoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        internal static string Jugar {
            get {
                return ResourceManager.GetString("Jugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        internal static string Listo {
            get {
                return ResourceManager.GetString("Listo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Memoriza la frase y haz clic en Siguiente.
        /// </summary>
        internal static string Memoriza_la_frase_y_haz_clic_en_siguiente {
            get {
                return ResourceManager.GetString("Memoriza_la_frase_y_haz_clic_en_siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO HAS LOGRADO COMPLETAR EL JUEGO.
        /// </summary>
        internal static string Mensaje_Rendirse {
            get {
                return ResourceManager.GetString("Mensaje_Rendirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 1.
        /// </summary>
        internal static string Nivel1 {
            get {
                return ResourceManager.GetString("Nivel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 2.
        /// </summary>
        internal static string Nivel2 {
            get {
                return ResourceManager.GetString("Nivel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 3.
        /// </summary>
        internal static string Nivel3 {
            get {
                return ResourceManager.GetString("Nivel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 4.
        /// </summary>
        internal static string Nivel4 {
            get {
                return ResourceManager.GetString("Nivel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 5.
        /// </summary>
        internal static string Nivel5 {
            get {
                return ResourceManager.GetString("Nivel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 6.
        /// </summary>
        internal static string Nivel6 {
            get {
                return ResourceManager.GetString("Nivel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  números por encontrar.
        /// </summary>
        internal static string Numeros_por_encontrar {
            get {
                return ResourceManager.GetString("Numeros_por_encontrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo.
        /// </summary>
        internal static string Objetivo {
            get {
                return ResourceManager.GetString("Objetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollar la atención selectiva del estudiante, que se trata de la capacidad de concentrarse en la información relevante mientras se ignoran las distracciones irrelevantes..
        /// </summary>
        internal static string Objetivo1 {
            get {
                return ResourceManager.GetString("Objetivo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollar la atención del estudiante, haciéndo que se centre únicamente en encontrar a Pikachu en las imágenes que se le va a mostrar..
        /// </summary>
        internal static string Objetivo2 {
            get {
                return ResourceManager.GetString("Objetivo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejorar la habilidad de atención selectiva del estudiante, de manera que al tener varios estímulos, preste atención únicamente a uno en concreto..
        /// </summary>
        internal static string Objetivo3 {
            get {
                return ResourceManager.GetString("Objetivo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejorar el razonamiento cuantitativo y las habilidades de resolución de problemas que son necesarias para tomar decisiones inteligentes, incluidas las que se relacionan con la memoria procedimental..
        /// </summary>
        internal static string Objetivo4 {
            get {
                return ResourceManager.GetString("Objetivo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollar la memoria del estudiante, trabajando con sus recuerdos temporales, mediante imágenes representativas. Además se pretende conseguir que el estudiante aprenda acerca de la cultura Ecuatoriana..
        /// </summary>
        internal static string Objetivo5 {
            get {
                return ResourceManager.GetString("Objetivo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollar la memoria a corto plazo así como la memoria espacial, haciendo que el estudiante recuerde el orden de las palabras que se le mostrarán en diferentes frases que forman una historia..
        /// </summary>
        internal static string Objetivo6 {
            get {
                return ResourceManager.GetString("Objetivo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBTUVISTE.
        /// </summary>
        internal static string Obtuviste {
            get {
                return ResourceManager.GetString("Obtuviste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fíjate bien, aún te faltan .
        /// </summary>
        internal static string Pista_a1_1 {
            get {
                return ResourceManager.GetString("Pista_a1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fíjate bien, aún te falta .
        /// </summary>
        internal static string Pista_a1_1_1 {
            get {
                return ResourceManager.GetString("Pista_a1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  letras por encontrar.
        /// </summary>
        internal static string Pista_a1_2 {
            get {
                return ResourceManager.GetString("Pista_a1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  letra por encontrar.
        /// </summary>
        internal static string Pista_a1_3 {
            get {
                return ResourceManager.GetString("Pista_a1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  número por encontrar.
        /// </summary>
        internal static string Pista_a1_4 {
            get {
                return ResourceManager.GetString("Pista_a1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A Pikachu le gustan los animales.
        /// </summary>
        internal static string Pista_a2_1 {
            get {
                return ResourceManager.GetString("Pista_a2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está cerca de un chico con un saco a rayas.
        /// </summary>
        internal static string Pista_a2_2 {
            get {
                return ResourceManager.GetString("Pista_a2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A Pikachu no le gusta el agua.
        /// </summary>
        internal static string Pista_a2_3 {
            get {
                return ResourceManager.GetString("Pista_a2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A su derecha hay un hombre de verde tomando el sol.
        /// </summary>
        internal static string Pista_a2_4 {
            get {
                return ResourceManager.GetString("Pista_a2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay gente cerca de él que está corriendo.
        /// </summary>
        internal static string Pista_a2_5 {
            get {
                return ResourceManager.GetString("Pista_a2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El color Rojo es la clave.
        /// </summary>
        internal static string Pista_a2_6 {
            get {
                return ResourceManager.GetString("Pista_a2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No importa lo que diga el Texto de abajo, únicamente debes fijarte en su COLOR y verificar si coincide con el significado.
        /// </summary>
        internal static string Pista_a3 {
            get {
                return ResourceManager.GetString("Pista_a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las provincias que se te mostraron anteriormente fueron: .
        /// </summary>
        internal static string Pista_m2 {
            get {
                return ResourceManager.GetString("Pista_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La historia era: .
        /// </summary>
        internal static string Pista_m3 {
            get {
                return ResourceManager.GetString("Pista_m3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las pistas estarán disponibles después de que completes la primera frase.
        /// </summary>
        internal static string Pistas_disponibles {
            get {
                return ResourceManager.GetString("Pistas_disponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego: &quot;Provincias del Ecuador&quot;.
        /// </summary>
        internal static string Provincias_del_Ecuador {
            get {
                return ResourceManager.GetString("Provincias_del_Ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PUNTOS, ¿QUÉ QUIERES HACER?.
        /// </summary>
        internal static string Puntos {
            get {
                return ResourceManager.GetString("Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué edad tienes?.
        /// </summary>
        internal static string Que_edad_tienes {
            get {
                return ResourceManager.GetString("Que_edad_tienes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerda que la edad que hemos puesto a cada juego, es la que recomendamos, pero puedes elegir el que quieras..
        /// </summary>
        internal static string Recuerda_que_la_edad {
            get {
                return ResourceManager.GetString("Recuerda_que_la_edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rendirse.
        /// </summary>
        internal static string Rendirse {
            get {
                return ResourceManager.GetString("Rendirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IR AL MENÚ.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Salir_del_juego {
            get {
                return ResourceManager.GetString("Salir_del_juego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SI.
        /// </summary>
        internal static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Significado.
        /// </summary>
        internal static string Significado {
            get {
                return ResourceManager.GetString("Significado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonido.
        /// </summary>
        internal static string Sonido {
            get {
                return ResourceManager.GetString("Sonido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego: &quot;Tablas de multiplicar&quot;.
        /// </summary>
        internal static string Tablas_de_multiplicar {
            get {
                return ResourceManager.GetString("Tablas_de_multiplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tema.
        /// </summary>
        internal static string Tema {
            get {
                return ResourceManager.GetString("Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo:.
        /// </summary>
        internal static string Tiempo {
            get {
                return ResourceManager.GetString("Tiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Universidad de las Fuerzas Armada ESPE sede Latacunga.
        /// </summary>
        internal static string Universidad {
            get {
                return ResourceManager.GetString("Universidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VER UN VIDEO.
        /// </summary>
        internal static string Ver_video {
            get {
                return ResourceManager.GetString("Ver_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VOLVER A JUGAR.
        /// </summary>
        internal static string Volver_a_jugar {
            get {
                return ResourceManager.GetString("Volver_a_jugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  y .
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
